name: Challenges-MongoConnector
version: 2.3.2
api-version: 1.14
author: CodingArea
authors:
  - anweisen
main: net.codingarea.challenges.mongoconnector.MongoConnector
depend:
  - Challenges
description: |
  Provides the needed depedencies to the ChallengesPlugin to conntent to a MongoDB database
