name: Challenges-MongoConnector
version: ${version}
api-version: 1.14
author: CodingArea
authors:
  - anweisen
main: net.codingarea.challenges.mongoconnector.MongoConnector
depend:
  - Challenges
description: |
  Provides the needed dependencies to the ChallengesPlugin to connect to a MongoDB database
