name: Qodana - Code Inspection
on:
  push:

jobs:
  qodana:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Qodana Scan
        uses: JetBrains/qodana-action@v2024.3.4